name: Build and Archive

on:
  # Triggers the workflow on push or pull request msgs but only for the "main" branch
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  App:
    runs-on: ubuntu-latest
    container:
      image: vladkosten/embedded_env:first
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: PiHMI
          path: ./build/App.elf
